import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";import {spawnSync} from "node:child_process";
test("Windows updater scripts parse and retain rollback controls",{skip:process.platform!=="win32"},()=>{for(const name of ["schedule-staged-update.ps1","apply-staged-update.ps1","update-server-deployment.ps1"]){const file=path.join(process.cwd(),"scripts",name);const command=`$t=$null;$e=$null;[System.Management.Automation.Language.Parser]::ParseFile('${file.replace(/'/g,"''")}',[ref]$t,[ref]$e)|Out-Null;if($e.Count){$e|% Message;exit 1}`;const result=spawnSync("powershell.exe",["-NoProfile","-Command",command],{encoding:"utf8"});assert.equal(result.status,0,result.stderr||result.stdout);}const apply=fs.readFileSync(path.join(process.cwd(),"scripts","apply-staged-update.ps1"),"utf8");for(const pattern of [/Get-FileHash/,/release-manifest/,/update-server-deployment\.ps1/,/HealthUrl/,/rolledBack/,/post-install-checklist\.json/,/deployment_output/,/Write-Receipt "failed"/,/stage=\$script:stage/])assert.match(apply,pattern);const deployment=fs.readFileSync(path.join(process.cwd(),"scripts","update-server-deployment.ps1"),"utf8");for(const pattern of [/Wait-SasHealth/,/Restore-Backup/,/Assert-Deployment/,/Copy-CertificateTree/,/RolledBack/,/backup_preflight/,/missingFiles/])assert.match(deployment,pattern);const scheduler=fs.readFileSync(path.join(process.cwd(),"scripts","schedule-staged-update.ps1"),"utf8");for(const pattern of [/ReceiptPath/,/Write-Receipt/,/"registered"/,/"started"/])assert.match(scheduler,pattern);assert.match(scheduler,/-ReceiptPath \$q\$ReceiptPath\$q/);});
test("service installer avoids unnecessary reconfiguration and preserves sc.exe diagnostics", { skip: process.platform !== "win32" }, () => {
  const installer = fs.readFileSync(path.join(process.cwd(), "scripts", "install-sas-services.ps1"), "utf8");
  for (const pattern of [/Win32_Service/,/Configuracion del servicio ya correcta/,/sc\.exe devolvio/,/WaitForStatus\('Running'/]) assert.match(installer, pattern);
});
test("server updater releases TURN and Node before copy and restores every prior service",()=>{
  const deployment=fs.readFileSync(path.join(process.cwd(),"scripts","update-server-deployment.ps1"),"utf8");
  for(const marker of ["SAS Support TURN","tools\\coturn\\turnserver.exe","Restore-SasSecondaryServices","Get-SasServiceSnapshot","Find-LatestValidBackup","rollbackPath"]) assert.equal(deployment.includes(marker),true,marker);
  assert.equal(deployment.includes("foreach ($serviceName in @('SAS Support Client Agent','SAS Support TURN','SAS Support Server'))"),true);
  assert.match(deployment,/No fue posible liberar todos los procesos de SAS/);
  assert.match(deployment,/La instalación actual está incompleta/);
});
