using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Windows.Forms;
internal static class Program
{
 private sealed class FrameMetrics{public double MeanLuma;public double LumaStdDev;public double DarkPixelRatio;public bool BlankFrame;}
 [STAThread] private static int Main(string[] args){int exit=1;Exception threadError=null;Thread worker=new Thread(()=>{try{exit=Array.Exists(args,a=>String.Equals(a,"--server",StringComparison.OrdinalIgnoreCase))?RunServer():Run(args);}catch(Exception ex){threadError=ex;}});worker.SetApartmentState(ApartmentState.MTA);worker.Start();worker.Join();if(threadError!=null){Console.Error.WriteLine(threadError.Message);return 1;}return exit;}
 private static int RunServer(){string line;while((line=Console.ReadLine())!=null){if(String.IsNullOrWhiteSpace(line))continue;try{string raw=Encoding.UTF8.GetString(Convert.FromBase64String(line.Trim()));Run(raw.Split(new[]{'\0'},StringSplitOptions.None));}catch(Exception ex){Console.WriteLine(ToJson(false,null,null,null,null,null,null,null,null,0,0,62,1280,DateTimeOffset.UtcNow.ToString("O"),"capture_server_request_invalid: "+ex.Message));}}return 0;}
 private static int Run(string[] args){CaptureOptions o=CaptureOptions.FromArgs(args);try{DesktopAccess.AttachToInputDesktop();Screen[] screens=Screen.AllScreens;Screen screen=screens.ElementAtOrDefault(o.MonitorIndex)??Screen.PrimaryScreen;if(screen==null)throw new InvalidOperationException("No screen detected.");Rectangle b=screen.Bounds;using(Bitmap source=new Bitmap(b.Width,b.Height,PixelFormat.Format24bppRgb)){using(Graphics g=Graphics.FromImage(source))g.CopyFromScreen(b.Location,Point.Empty,b.Size);FrameMetrics metrics=MeasureFrame(source);using(Graphics g=Graphics.FromImage(source))DrawCursor(g,b);double scale=o.NativeResolution?1.0:Math.Min(1.0,o.MaxWidth/(double)b.Width);int width=Math.Max(1,(int)Math.Round(b.Width*scale)),height=Math.Max(1,(int)Math.Round(b.Height*scale));using(Bitmap target=new Bitmap(width,height,PixelFormat.Format24bppRgb)){using(Graphics g=Graphics.FromImage(target)){g.CompositingQuality=CompositingQuality.HighSpeed;g.InterpolationMode=InterpolationMode.Low;g.SmoothingMode=SmoothingMode.HighSpeed;g.DrawImage(source,0,0,width,height);}using(MemoryStream stream=new MemoryStream()){ImageCodecInfo encoder=ImageCodecInfo.GetImageEncoders().First(c=>c.MimeType=="image/jpeg");using(EncoderParameters p=new EncoderParameters(1)){p.Param[0]=new EncoderParameter(System.Drawing.Imaging.Encoder.Quality,o.Quality);target.Save(stream,encoder,p);}string json=ToJson(true,"image/jpeg",Convert.ToBase64String(stream.ToArray()),width,height,b.Width,b.Height,b.X,b.Y,o.MonitorIndex,screens.Length,o.Quality,o.MaxWidth,DateTimeOffset.UtcNow.ToString("O"),null,metrics);WriteResult(o.ResultFile,json);}}}return 0;}catch(Exception ex){Console.Error.WriteLine(ex.Message);string json=ToJson(false,null,null,null,null,null,null,null,null,o.MonitorIndex,Screen.AllScreens.Length,o.Quality,o.MaxWidth,DateTimeOffset.UtcNow.ToString("O"),ex.Message);WriteResult(o.ResultFile,json);return 1;}}
 private static FrameMetrics MeasureFrame(Bitmap image){int stepX=Math.Max(1,image.Width/64),stepY=Math.Max(1,image.Height/64),count=0,dark=0;double sum=0,squares=0;for(int y=stepY/2;y<image.Height;y+=stepY)for(int x=stepX/2;x<image.Width;x+=stepX){Color color=image.GetPixel(x,y);double luma=0.2126*color.R+0.7152*color.G+0.0722*color.B;sum+=luma;squares+=luma*luma;if(luma<8)dark++;count++;}double mean=count>0?sum/count:0,variance=count>0?Math.Max(0,squares/count-mean*mean):0,ratio=count>0?dark/(double)count:1;return new FrameMetrics{MeanLuma=mean,LumaStdDev=Math.Sqrt(variance),DarkPixelRatio=ratio,BlankFrame=ratio>=0.995&&mean<=3&&Math.Sqrt(variance)<=4};}
 private static void DrawCursor(Graphics graphics,Rectangle bounds){CURSORINFO cursor=new CURSORINFO();cursor.cbSize=Marshal.SizeOf(typeof(CURSORINFO));if(!GetCursorInfo(ref cursor)||(cursor.flags&1)==0||cursor.hCursor==IntPtr.Zero)return;ICONINFO icon=new ICONINFO();int hotX=0,hotY=0;try{if(GetIconInfo(cursor.hCursor,out icon)){hotX=(int)icon.xHotspot;hotY=(int)icon.yHotspot;}IntPtr hdc=graphics.GetHdc();try{DrawIconEx(hdc,cursor.ptScreenPos.X-bounds.X-hotX,cursor.ptScreenPos.Y-bounds.Y-hotY,cursor.hCursor,0,0,0,IntPtr.Zero,3);}finally{graphics.ReleaseHdc(hdc);}}finally{if(icon.hbmMask!=IntPtr.Zero)DeleteObject(icon.hbmMask);if(icon.hbmColor!=IntPtr.Zero)DeleteObject(icon.hbmColor);}}
 [DllImport("user32.dll",SetLastError=true)]private static extern bool GetCursorInfo(ref CURSORINFO info);
 [DllImport("user32.dll",SetLastError=true)]private static extern bool GetIconInfo(IntPtr icon,out ICONINFO info);
 [DllImport("user32.dll",SetLastError=true)]private static extern bool DrawIconEx(IntPtr hdc,int x,int y,IntPtr icon,int width,int height,int step,IntPtr brush,int flags);
 [DllImport("gdi32.dll")]private static extern bool DeleteObject(IntPtr value);
 [StructLayout(LayoutKind.Sequential)]private struct POINT{public int X,Y;}
 [StructLayout(LayoutKind.Sequential)]private struct CURSORINFO{public int cbSize,flags;public IntPtr hCursor;public POINT ptScreenPos;}
 [StructLayout(LayoutKind.Sequential)]private struct ICONINFO{[MarshalAs(UnmanagedType.Bool)]public bool fIcon;public uint xHotspot,yHotspot;public IntPtr hbmMask,hbmColor;}
 private static void WriteResult(string file,string json){if(!String.IsNullOrEmpty(file)){Directory.CreateDirectory(Path.GetDirectoryName(file));File.WriteAllText(file,json,Encoding.UTF8);}Console.WriteLine(json);}
 private static string ToJson(bool ok,string mime,string image,int? width,int? height,int? nativeWidth,int? nativeHeight,int? originX,int? originY,int monitorIndex,int monitorCount,long quality,int maxWidth,string capturedAt,string error,FrameMetrics metrics=null){string frameMetrics=metrics==null?"null":"{\"meanLuma\":"+metrics.MeanLuma.ToString("F3",System.Globalization.CultureInfo.InvariantCulture)+",\"lumaStdDev\":"+metrics.LumaStdDev.ToString("F3",System.Globalization.CultureInfo.InvariantCulture)+",\"darkPixelRatio\":"+metrics.DarkPixelRatio.ToString("F5",System.Globalization.CultureInfo.InvariantCulture)+"}";return "{\"ok\":"+(ok?"true":"false")+",\"mimeType\":"+Q(mime)+",\"imageBase64\":"+Q(image)+",\"width\":"+N(width)+",\"height\":"+N(height)+",\"nativeWidth\":"+N(nativeWidth)+",\"nativeHeight\":"+N(nativeHeight)+",\"monitorOriginX\":"+N(originX)+",\"monitorOriginY\":"+N(originY)+",\"monitorIndex\":"+monitorIndex+",\"monitorCount\":"+monitorCount+",\"quality\":"+quality+",\"maxWidth\":"+maxWidth+",\"frameMetrics\":"+frameMetrics+",\"blankFrame\":"+(metrics!=null&&metrics.BlankFrame?"true":"false")+",\"capturedAt\":"+Q(capturedAt)+",\"error\":"+Q(error)+"}";}
 private static string N(int? v){return v.HasValue?v.Value.ToString():"null";}private static string Q(string v){return v==null?"null":"\""+v.Replace("\\","\\\\").Replace("\"","\\\"").Replace("\r","\\r").Replace("\n","\\n")+"\"";}
}
internal static class DesktopAccess
{
 private const uint DESKTOP_READOBJECTS=0x0001,DESKTOP_CREATEWINDOW=0x0002,DESKTOP_WRITEOBJECTS=0x0080,DESKTOP_SWITCHDESKTOP=0x0100;
 [DllImport("user32.dll",SetLastError=true)]private static extern IntPtr OpenInputDesktop(uint flags,bool inherit,uint access);
 [DllImport("user32.dll",SetLastError=true)]private static extern bool SetThreadDesktop(IntPtr desktop);
 private static IntPtr inputDesktop=IntPtr.Zero;
 internal static void AttachToInputDesktop(){uint access=DESKTOP_READOBJECTS|DESKTOP_CREATEWINDOW|DESKTOP_WRITEOBJECTS|DESKTOP_SWITCHDESKTOP;inputDesktop=OpenInputDesktop(0,false,access);if(inputDesktop==IntPtr.Zero)throw new InvalidOperationException("input_desktop_unavailable: "+Marshal.GetLastWin32Error());if(!SetThreadDesktop(inputDesktop))throw new InvalidOperationException("input_desktop_attach_failed: "+Marshal.GetLastWin32Error());}
}
internal sealed class CaptureOptions{public long Quality;public int MaxWidth;public int MonitorIndex;public bool NativeResolution;public string ResultFile="";public static CaptureOptions FromArgs(string[] args){CaptureOptions o=new CaptureOptions();o.Quality=62;o.MaxWidth=1280;for(int i=0;i<args.Length;i++){string a=args[i],n=i+1<args.Length?args[i+1]:null;long l;int v;if(a=="--quality"&&Int64.TryParse(n,out l)){o.Quality=Math.Max(35,Math.Min(90,l));i++;}else if(a=="--max-width"&&Int32.TryParse(n,out v)){o.MaxWidth=Math.Max(640,Math.Min(3840,v));i++;}else if(a=="--monitor"&&Int32.TryParse(n,out v)){o.MonitorIndex=Math.Max(0,Math.Min(15,v));i++;}else if(a=="--native")o.NativeResolution=true;else if(a=="--result-file"){o.ResultFile=n;i++;}}return o;}}
